#!/usr/bin/python

import random
import sys

if (len(sys.argv) != 2):
	sys.exit("Usage: random-list-generator <size of list>")

try:
	data = range(1, int(sys.argv[1]) + 1, 1)
except:
	sys.exit("Argument must be an integer")

random.shuffle(data)
string = " ".join(str(num) for num in data)
print(string)
